services:
  - type: web
    name: alx-project-nexus-web
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput || echo "Warning: Collectstatic failed, but continuing build"
    startCommand: gunicorn ecommerce.wsgi:application --bind 0.0.0.0:$PORT --workers 4 --threads 4
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: neondb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
      - key: DJANGO_SETTINGS_MODULE
        value: "ecommerce.settings"
    plan: free
    numInstances: 1
