services:
  - type: web
    name: alx-project-nexus
    env: python
    buildCommand: "./setup.sh"
    startCommand: "gunicorn ecommerce.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "alx-project-nexus-3ozp.onrender.com localhost 127.0.0.1"
      - key: DJANGO_SETTINGS_MODULE
        value: "ecommerce.settings"
      - key: DATABASE_URL
        fromDatabase:
          name: alx-project-nexus-db
          property: connectionString