# Render Configuration File
# Reference: https://render.com/docs/deploy-render-yaml

# Global settings for all services
globals:
  envVars:
    - key: PYTHON_VERSION
      value: 3.11.7
    - key: PYTHONUNBUFFERED
      value: 1
    - key: PYTHONDONTWRITEBYTECODE
      value: 1

# Define the services to deploy
services:
  # Web service (Django)
  - type: web
    name: alx-project-nexus-web
    env: docker
    region: oregon
    plan: free
    dockerfile: Dockerfile
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 4 ecommerce.wsgi:application
    envVars:
      - key: SECRET_KEY
        value: ucuqp5616lwcb8&ne1-a^r*^rs9%!-wa$t!m@zbrog60u=cj_7
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_NKBSZ0n3Tzeu@ep-silent-resonance-a8om4bn6-pooler.eastus2.azure.neon.tech/neondb?sslmode=require&channel_binding=require
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          type: redis
          property: connectionString
      - key: CORS_ALLOWED_ORIGINS
        value: "http://localhost:3000,https://your-production-domain.com"
      - key: FRONTEND_URL
        value: "https://your-production-domain.com"  # Update to your actual frontend domain
      - key: DEFAULT_SHIPPING_COST
        value: "10.00"
      - key: TAX_RATE
        value: "0.16"
    buildEnvVars:
      - key: ALLOWED_HOSTS
        value: "*"
      - key: SECRET_KEY
        value: dummy-key-for-build
      - key: FRONTEND_URL
        value: "http://localhost:3000"  # Default for build phase
    autoDeploy: true
    numInstances: 1
    healthCheckPath: /
    healthCheckTimeout: 120

  # Celery worker
  - type: worker
    name: alx-project-nexus-worker
    env: docker
    region: oregon
    plan: free
    dockerfile: Dockerfile
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: celery -A ecommerce worker -l info
    envVars:
      - key: SECRET_KEY
        value: ucuqp5616lwcb8&ne1-a^r*^rs9%!-wa$t!m@zbrog60u=cj_7
      - key: ALLOWED_HOSTS
        value: "*"
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_NKBSZ0n3Tzeu@ep-silent-resonance-a8om4bn6-pooler.eastus2.azure.neon.tech/neondb?sslmode=require&channel_binding=require
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          type: redis
          property: connectionString
      - key: FRONTEND_URL
        value: "https://your-production-domain.com"  # Update to your actual frontend domain
    buildEnvVars:
      - key: ALLOWED_HOSTS
        value: "*"
      - key: SECRET_KEY
        value: dummy-key-for-build
      - key: FRONTEND_URL
        value: "http://localhost:3000"  # Default for build phase
    autoDeploy: true

  # Redis service
  - type: redis
    name: alx-project-nexus-redis
    plan: free# Render Configuration File
# Reference: https://render.com/docs/deploy-render-yaml

# Global settings for all services
globals:
  envVars:
    - key: PYTHON_VERSION
      value: 3.11.7
    - key: PYTHONUNBUFFERED
      value: 1
    - key: PYTHONDONTWRITEBYTECODE
      value: 1

# Define the services to deploy
services:
  # Web service (Django)
  - type: web
    name: alx-project-nexus-web
    env: docker
    region: oregon
    plan: free
    dockerfile: Dockerfile
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 4 ecommerce.wsgi:application
    envVars:
      - key: SECRET_KEY
        value: ucuqp5616lwcb8&ne1-a^r*^rs9%!-wa$t!m@zbrog60u=cj_7
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_NKBSZ0n3Tzeu@ep-silent-resonance-a8om4bn6-pooler.eastus2.azure.neon.tech/neondb?sslmode=require&channel_binding=require
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          type: redis
          property: connectionString
      - key: CORS_ALLOWED_ORIGINS
        value: "http://localhost:3000,https://your-production-domain.com"
      - key: DEFAULT_SHIPPING_COST
        value: "10.00"
      - key: TAX_RATE
        value: "0.16"
    buildEnvVars:
      - key: ALLOWED_HOSTS
        value: "*"
      - key: SECRET_KEY
        value: dummy-key-for-build
    autoDeploy: true
    numInstances: 1
    healthCheckPath: /
    healthCheckTimeout: 120

  # Celery worker
  - type: worker
    name: alx-project-nexus-worker
    env: docker
    region: oregon
    plan: free
    dockerfile: Dockerfile
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: celery -A ecommerce worker -l info
    envVars:
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          type: redis
          property: connectionString
      - key: SECRET_KEY
        value: ucuqp5616lwcb8&ne1-a^r*^rs9%!-wa$t!m@zbrog60u=cj_7
      - key: ALLOWED_HOSTS
        value: "*"
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_NKBSZ0n3Tzeu@ep-silent-resonance-a8om4bn6-pooler.eastus2.azure.neon.tech/neondb?sslmode=require&channel_binding=require
    buildEnvVars:
      - key: ALLOWED_HOSTS
        value: "*"
      - key: SECRET_KEY
        value: dummy-key-for-build
    autoDeploy: true

  # Redis service
  - type: redis
    name: alx-project-nexus-redis
    plan: free
    region: oregon